apiVersion: v1
kind: Service
metadata:
  name: juiceshop-nybbleacm-service
  labels:
    app: juiceshop-nybbleacm-deployment
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: juiceshop-nybbleacm-deployment
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: juiceshop-nybbleacm-deployment
spec:
  selector:
    matchLabels:
      app: juiceshop-nybbleacm-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: juiceshop-nybbleacm-deployment
    spec:
      containers:
      - name: master
        image: nybbleacademy/juiceshop
        ports:
        - containerPort: 3000