name: Build
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
    # Install tools
        - name: Run Sonar
          run: npm install
        - name: Run Sonar
          run: cd frontend && npm run sonar          