name: Sonar on PR
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    name: Sonar on PR
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '12.x'
# Install tools
        - name: Run Sonar
          run: cd frontend && npm install
        - name: Run Sonar
          run: cd frontend && npm run sonar          